apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-web
  labels:
    app: loadbalancer-example

spec:
  selector:
    matchLabels:
      app: loadbalancer-example
  replicas: 7
  template:
    metadata:
      labels:
        app:  loadbalancer-example
      annotations:
        prometheus.io/scrape: 'true'
        rometheus.io/port: '80'
        prometheus.io/path: '/data/metrics'
    spec:
      containers:
      - name: cloud-nativist
        image:  docker.io/cloudnat/black-hoc:latest
        ports:
        - containerPort:  80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: loadbalancer-example
  type: LoadBalancer
  ports:
  - name: my-service
    protocol: TCP
    port: 80 
    targetPort: 80
    nodePort: 30163